name: Build & Deploy SvelteKit

on:
    push:
        branches: [main]

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22"
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Build SvelteKit
              run: npm run build

            - name: Prepare deploy dir
              run: |
                  # mkdir -p ./deploy
                  # cp -r build ./deploy/
                  cp package.json /var/www/fe-alih-media
                  cp package-lock.json /var/www/fe-alih-media

            - name: Create target directory on VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SECRET }}
                  port: 22
                  script: |
                      mkdir -p /var/www/fe-alih-media

            - name: Upload built app
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SECRET }}
                  port: 22
                  source: "build"
                  target: /var/www/fe-alih-media
            # - name: Upload built app
            #   uses: appleboy/scp-action@v0.1.4
            #   with:
            #       host: ${{ secrets.VPS_HOST }}
            #       username: ${{ secrets.VPS_USER }}
            #       key: ${{ secrets.VPS_SECRET }}
            #       port: 22
            #       source: |
            #           build
            #           package.json
            #           package-lock.json
            #       target: /var/www/fe-alih-media

            - name: Install dependencies
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SECRET }}
                  port: 22
                  script: |
                      cd /var/www/fe-alih-media
                      npm install --omit=dev

            - name: Restart pm2
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SECRET }}
                  port: 22
                  script: pm2 restart fe-alih-media
